#!/usr/bin/env python

import os
import sys
import yaml
from subprocess import call

def process_apt(dct):
    exists = not call('which apt-get', shell='True')
    if exists:
        pkgs = []
        pkgs.extend(dct.get('dev', []))
        pkgs.extend(dct.get('install', []))

        os.system('apt-get update')
        os.system('apt-get install -y {}'.format(' '.join(pkgs)))

def main(args):
    fpath = args[0]

    with open(fpath, 'r') as f:
        dct = yaml.load(f)

    if dct:
        if 'apt' in dct:
            process_apt(dct['apt'])

if __name__ == '__main__':
    main(sys.argv[1:])
